### ISSUE TITLE
Subgraph with new Registry, Factory and PrincipalToken but without LPVault - Sepolia

### ISSUE THREAD

**Issue by localtechboy** [perspectivefi/spectra-subgraph#132]
### Docs
https://www.notion.so/perspectivefi/BETA-3-Sepolia-444e4400235f4519856ce7c1736ff385

### Contracts

- **Registry**
https://sepolia.etherscan.io/address/0x89E28ca7Fe29F535D91Dab47493bBFB2c8f0166b#events

- **Factory**
https://sepolia.etherscan.io/address/0x4774e9bA6517b5e22F580163611d26dadf59DE7C#code

- **PrincipalToken**
https://sepolia.etherscan.io/address/0xD75C5AB96B284D61E7B6bED352db7Cf7cbaD720A#code

### TODO
- [x] Create new subgraph using TheGraph Studio (https://thegraph.com/studio/subgraph/spectra-subgraph-sepolia/)
- [x] Using new contract deployed on the new testnet - Sepolia, update Spectra subgraph so it will be able to handle new events. 
- [x] Remove LPVault triggers from index
- [ ] Replace Deposit/Withdraw by Mint/Redeem
- [ ] Adjust unit tests
